//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl_doan_severAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public string maDH { get; set; }
        public string useName { get; set; }
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string anh { get; set; }
        public Nullable<int> donGia { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> tongTien { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
