//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl_doan_severAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public string maDH { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<double> phiGiaoHang { get; set; }
        public string ghiChu { get; set; }
        public string diaChiGuiHang { get; set; }
        public Nullable<double> tongTienThanhToan { get; set; }
    
        public virtual CHITIETDONHANG CHITIETDONHANG { get; set; }
    }
}
