//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl_doan_severAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public string Id { get; set; }
        public string useName { get; set; }
        public string passWord { get; set; }
        public string SDT { get; set; }
        public string diaChi { get; set; }
    }
}
